### ISSUE TITLE
进游戏死机

### ISSUE THREAD

**Issue by kidxiang** [sskyNS/RoastDuck-CFWPack#1]
用的release里的最新版
首版软破机，17.0.0的系统，玩《尼罗河勇士2》，一出征就死机，发出极大的噪音，还以为机器就挂了，真是吓死人，不敢再用这个整合包了

另外，用刺心的1.6.2的整合包就没有问题

**Comment by sskyNS** [comment]
软破机器？你是否开启了极限超频，比如ram：2400MHz？

**Comment by sskyNS** [comment]
不用担心，这是超频过高的常见问题，选择合适的频率比如1996或者1600的ram数值会比较适合V1机器（软破普通版机器）

**Comment by kidxiang** [comment]
没有超频，至少我没有进入特斯拉去设置过，就刚拷贝了这个release的整合包，就进系统进游戏。
如果整合包的默认设置是超频了，那就有可能超了，如果默认设置没有超，我没去设置超频。

还有个奇怪的现象，玩从刺心的1.6.1换到这个整合包，pro手柄需要重新配对，但从这个换回刺心，pro手柄不需要重新配对（不知道是以前的刺心整合包配对过，不用再配对；还是在这个整合包配对后，就自动配对了）

**Comment by sskyNS** [comment]
你说的是蓝牙手柄插件还是JC？

**Comment by kidxiang** [comment]
蓝牙手柄插件我还没用过，就是任天堂原装的pro手柄

**Comment by sskyNS** [comment]
嗯，一般而言需要重新配对一次（在虚拟系统中） 但是在大气层某一个版本更新之后，他会继承继承真实系统或者正版系统的蓝牙配对信息，我稍后会检查部分代码。

**Comment by ffgckf** [comment]
> 不用担心，这是超频过高的常见问题，选择合适的频率比如1996或者1600的ram数值会比较适合V1机器（软破普通版机器）

请问一下国行OLED，RAM适合长期2400吗？

**Comment by sskyNS** [comment]
> > 不用担心，这是超频过高的常见问题，选择合适的频率比如1996或者1600的ram数值会比较适合V1机器（软破普通版机器）
> 
> 请问一下国行OLED，RAM适合长期2400吗？

需要经过压力测试，对于不同机器数值略有不同

**Comment by sskyNS** [comment]
```          Core 0  Core 1  Core 2  Core 3  Core 4  Core 5  Core 6
[start A]   3   ↔   3   ↔   3   ↔   3   ↔   3   ↔   3   ↔   3   
            ↓       ↓       ↓       ↓       ↓       ↓       ↓   
[start B]   4   ↔   4   ↔   4   ↔   4   ↔   4   ↔   4   ↔   4   
            ↓       ↓       ↓       ↓       ↓       ↓       ↓   
            5       5       5       5       5       5       5   
            ↓       ↓       ↓       ↓       ↓       ↓       ↓   
            6       6       6       6       6       6       6   
```

**Comment by sskyNS** [comment]
mine ended like this. ```          Core 0  Core 1  Core 2  Core 3  Core 4  Core 5  Core 6
[start A]   3   ↔   3   ↔   3   ↔   3   ↔   3   ↔   3   ↔   3   
            ↓       ↓       ↓       ↓       ↓       ↓       ↓   
[start B]   4   ↔   4   ↔   4   ↔   4   ↔   4   ↔   4   ↔   4   
            ↓       ↓       ↓       ↓               ↓       ↓   
            5       5       5       5               5       5   
            ↓                                                   
            6                                                   
```

**Comment by sskyNS** [comment]
This is my friend's method. You can consider this suggestion and test it step by step to finally meet your requirements.

**Comment by sskyNS** [comment]
频率：2400-2500左右，尽可能不要超过2500，降压设置从低到高
