### ISSUE TITLE
GPU超频频率只能到614，选择到更高频率最大也只能614，cpu和内存超频正常，功能正常

### ISSUE THREAD

**Issue by watson0510** [sskyNS/RoastDuck-CFWPack#2]
GPU超频频率只能到614，选择到更高频率最大也只能614，cpu和内存超频正常，功能正常，有大佬知道这个问题吗，感觉全网都没答案

**Comment by sskyNS** [comment]
根据原作者的回答，需要插电才能解锁，并且是真实的频率。

**Comment by sskyNS** [comment]
已上传GPU解锁版本，可在v8.4.8中进行下载更新。
但是请谨慎使用，这是我的提醒也是为什么没有放入主要更新中的原因之一。
[https://github.com/sskyNS/RoastDuck-CFWPack/releases/tag/V8.4.8](url)

**Comment by watson0510** [comment]
收到，谢谢
