### ISSUE TITLE
能否更新繁體中文版本

### ISSUE THREAD

**Issue by tsaijohn** [sskyNS/RoastDuck-CFWPack#3]
8.4.0後都只有簡中，繁體中文系統下會缺字，如果需要我也可以幫忙。

**Comment by sskyNS** [comment]
提供你当前繁体中文的界面截图，我需要知道哪些部分需要进行繁体化（实际并不花费太多时间，你只需要告诉我哪里需要繁体即可）

**Comment by tsaijohn** [comment]
主要是ultrahand (L+下) 呼叫出系統選單的部分
![2023110409322500 1](https://github.com/sskyNS/RoastDuck-CFWPack/assets/24467145/a38d5cf7-8dab-405e-920d-651c44bd0aae)
![2023110409322800 1](https://github.com/sskyNS/RoastDuck-CFWPack/assets/24467145/247c8e1b-ceb3-4076-9add-f644adf4974a)
![2023110409323600 1](https://github.com/sskyNS/RoastDuck-CFWPack/assets/24467145/1eed4ab7-fd64-4ff1-8258-6f554fb181e6)
這附近的缺字比較影響使用

**Comment by sskyNS** [comment]
[繁体ovl.zip](https://github.com/sskyNS/RoastDuck-CFWPack/files/13256768/ovl.zip)
已上传，后续如果有问题请在这里留言。

**Comment by sskyNS** [comment]
Ultrahand自带繁体中文翻译，“+”进入语言选择，选择zh-TW
