### ISSUE TITLE
bin格式的amiibo可以直接用吗？

### ISSUE THREAD

**Issue by dyf991645** [sskyNS/RoastDuck-CFWPack#4]
你好，整合包里的amiibo是bin格式的，emuiibo中是空的，放入json格式的可以正常使用。
包里为什么自带bin格式？

**Comment by sskyNS** [comment]
自行烧录amiibo，整合包内amiibo为网络随机采集

**Comment by sskyNS** [comment]
烤鸭包于v8.5.0版本（甚至更早）已经集成完美amiibo显示模块，仅作提醒。 [https://github.com/sskyNS/RoastDuck-CFWPack/releases/download/V8.5.0/V8.5.0.7z](url)
