### ISSUE TITLE
这上传的什么玩意？

### ISSUE THREAD

**Issue by robertzycheng** [sskyNS/RoastDuck-CFWPack#5]
这1G的玩意，误导人吧

**Comment by sskyNS** [comment]
如存在误导，请提供您被误导的证明。

**Comment by sskyNS** [comment]
[https://github.com/sskyNS/RoastDuck-CFWPack/releases/tag/V8.4.8](url)
**其中包含了较多的内容分支，包含之前的所有版本内容，包括其他分支内容，选择适合自己的下载使用即可。** #2
