### ISSUE TITLE
烤鸭您好，咨询两个问题

### ISSUE THREAD

**Issue by yangyi860** [sskyNS/RoastDuck-CFWPack#7]
烤鸭您好，我在使用您提供的8.5包的时候发现有两个问题：
1，手持时超频gpu最高就到614，不知道如何操作才能解除这一限制。
2、从游戏切出相册想通过edizon进行金手指地址搜索时（手动使用金手指）容易灰屏卡死，就是点相册后看不到相册里面的那些插件，屏幕显示为灰色，并且任何操作都无效，包括呼出特斯拉、按home键等等，只能手动强制重启。目前其他功能使用良好。
另外，再打扰一下，我对于OC中的有些功能不知道如何使用，找了很久的教程也找不到，尤其是降压的概念和实际操作、cpu、gpu、内存频率和电压的对应关系及操作细节、最后就是时序（完全无法理解）。因为我在尝试超频的时候总是容易出现花屏，死机的状况，去搜索了资料，说是要调整电压和时序，调节电压我还好理解一点（把饭吃饱，才有力气干活），但那个时序我完全就是一脸懵，完全不知道怎么调节，因为不知道时序含义和为了解决什么问题。以上，给您添麻烦了！

**Comment by sskyNS** [comment]
对于当前Switch游戏机，最安全的1581/614，这是CPU和GPU的安全值，并且烤鸭包并不是以超频作为主要分发手段，所以对于开放版本我并不提供手持解锁版本，仅仅是为了避免任何意外事件。
Edizon搜索内存卡死情况十分常见，仅对于系统运存不足的情况下会发生，尝试关闭“后台应用”中的任意两个插件（至少），关闭后重新开机并运行你所要做的游戏，部分大型游戏可能仍然存在爆内存的问题，但这样的游戏不多。
对于电压的理解毫无疑问你说的基本是对的，部分高频率的内存、CPU灯需要较高的电压提供才能完成，否则无法开机。对于时序，推荐按照以下顺序进行一次测试，直到你找到完美的答案。
![IMG_9448](https://github.com/sskyNS/RoastDuck-CFWPack/assets/121209531/80ed8d4f-2cc1-48eb-a2ea-b45cbc461b96)
![IMG_9447](https://github.com/sskyNS/RoastDuck-CFWPack/assets/121209531/2f5a049b-3768-4a17-adf4-2bef51b7597e)

**Comment by yangyi860** [comment]
谢谢解答~
