### ISSUE TITLE
如何下载release版本

### ISSUE THREAD

**Issue by zzyt1998** [sskyNS/RoastDuck-CFWPack#9]
烤鸭您好。请问如何在release链接里下载？我进去后看只能下载两个source code的压缩文件在asset里面，请问哪里可以下载安装包谢谢

**Comment by aaakoako** [comment]
您好！我已收到您的邮件！

**Comment by sskyNS** [comment]
我正在修改它，等我有时间我会上传较新的18.0.1的版本。

**Comment by zzyt1998** [comment]
感谢！

**Comment by sskyNS** [comment]
https://github.com/sskyNS/RoastDuck-CFWPack/releases/tag/V8.8.2

**Comment by zzyt1998** [comment]
感谢分享，我下载到sd卡后无法进入系统。看到三上烤鸭画面后提示了![image](https://github.com/sskyNS/RoastDuck-CFWPack/assets/40698742/84e8e183-988b-48b8-8890-b593fa4bed44)。我尝试了从新格式话fat32格式，然后用pkg1/2恢复归位档都还是提示这个错误界面，能麻烦大大指导下是哪里出问题了吗？万分感谢

**Comment by sskyNS** [comment]
机器的类型/真实系统固件版本/此前的系统是大气层还是TX？

**Comment by zzyt1998** [comment]
我用的是初代的switch，真实系统是8.1的。我有两个SD卡一个TX，一个大气层，我把大气层的卡安说明装了下，然后提示以上错误~不知道我哪里出了问题

**Comment by sskyNS** [comment]
抱歉，建议使用你的正常机器，暂时没有时间处理你的问题。

**Comment by sskyNS** [comment]
注意boot0-1
